version: "3"
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - dev.env
    volumes:
      - .:/app
    ports:
      - "${HOST:-8000}:${HOST:-8000}"
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:latest
    container_name: dealver_mysql
    ports:
      - "3306:3306"
    env_file:
      - dev.env
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data:
